name: Release

defaults:
  run:
    shell: bash

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v2
      - run: ls -ltr
      - run: npm ci
      - run: npm run setup
      - run: npm test
      - run: npm run publish -- ${{env.GITHUB_REF}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
